### ISSUE TITLE
System font size doesn't scale with ElvUI font size

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#447]
![wowscrnshot_011319_190228_li](https://user-images.githubusercontent.com/6052285/51088946-36806d00-1766-11e9-8202-a2d47e44407e.jpg)
![wowscrnshot_011319_190231_li](https://user-images.githubusercontent.com/6052285/51088947-36806d00-1766-11e9-9516-de5e94913a9f.jpg)

As you can see on the screenshots the system font size of context menues (rightclick on something) or inside of other addons doesn't scale with the font size set in ElvUI. I lowered the font size in ElvUI from 11 to 9 but the rest stay at value 11 I think.

Accorded to: https://github.com/ElvUI-TBC/ElvUI/issues/379

**Comment by Apollyonn** [comment]
Try this https://github.com/ElvUI-TBC/ElvUI/commit/b54dab96c8282b6489c84fb714f3118020d5b612, i think it should solve the issue and also this https://github.com/ElvUI-TBC/ElvUI/issues/439

**Comment by fatlus** [comment]
This fixes https://github.com/ElvUI-TBC/ElvUI/issues/439 but the font size is still the same

**Comment by Apollyonn** [comment]
![wowscrnshot_011419_005352](https://user-images.githubusercontent.com/19589902/51091711-ec63af80-1796-11e9-9dbb-983dce040852.jpg)

**Comment by fatlus** [comment]
Yes you are right, thanks for work!
